# Generated by Django 4.2.1 on 2023-05-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeGrupo', models.CharField(max_length=40)),
                ('icon_grupo', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'grupoMenu',
            },
        ),
        migrations.CreateModel(
            name='ItensMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=40)),
                ('icon_item', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=80)),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.grupomenu')),
            ],
            options={
                'db_table': 'ItensMenu',
            },
        ),
    ]
