# Generated by Django 4.2 on 2023-05-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomenu',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='itensmenu',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.permission'),
        ),
    ]
