# Generated by Django 4.2 on 2023-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_grupomenu_permission_itensmenu_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomenu',
            name='codigo',
            field=models.CharField(default='codigo default', max_length=40),
        ),
        migrations.AddField(
            model_name='itensmenu',
            name='codigo',
            field=models.CharField(default='codigo default', max_length=40),
        ),
    ]
