# Generated by Django 4.2 on 2023-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do usuário')),
                ('usuario_datasul', models.CharField(max_length=50, verbose_name='Usuário datasul')),
                ('usuario_fluig', models.CharField(max_length=100, verbose_name='Usuário Fluig')),
                ('is_active', models.BooleanField(default=False, verbose_name='usuario ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='usuario é da equipe de desenvolvimento?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='usuario é um superusuário?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
    ]
